name: $(SourceBranchName)_$(Date:yyyyMMdd).$(Rev:r)
pool:
  name: Default
  demands:
    - agent.os -equals Linux

trigger:
  - master

resources:
  - repo: self

variables:
  imageRepository: 'simployer-mcp-alexis'
  containerRegistry: 'acrsimployertechdev'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: $(Build.BuildNumber)

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        # pool:
        #   vmImage: $(vmImageName)
        steps:
          - script:  |
              if [ "$(Build.SourceBranch)" = "refs/heads/master" ]; then
              echo "##vso[task.setvariable variable=tag]$(Build.BuildNumber),latest"
              echo "Adding the latest tag for master"
              fi
          - task: Docker@2
            inputs:
              containerRegistry: $(containerRegistry)
              command: 'login'
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(containerRegistry)
              buildContext:  $(Build.SourcesDirectory)/
              tags: |
                $(tag)
          - task: CopyFiles@2
            inputs:
              SourceFolder: $(Build.SourcesDirectory)/ops/
              Contents: 'values.yaml'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              flattenFolders: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: 'Publish Artifact:drop'